apiVersion: apps/v1
kind: Deployment
metadata:
  name: loan-deployment
  labels:
    app: loan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loan
  template:
    metadata:
      labels:
        app: loan
    spec:
      containers:
        - name: database
          image: ziembatomasz/database:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 3306
        - name: product
          image: ziembatomasz/product:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8082
        - name: customer
          image: ziembatomasz/customer:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
        - name: credit
          image: ziembatomasz/credit:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8080