version: '3.3'

services:
  credit:
    image: ziembatomasz/credit:1.0
    environment:
      - MYSQL_HOST=database
    ports:
      - "8080:8080"
    links:
      - database

  customer:
    image: ziembatomasz/customer:1.0
    environment:
      - MYSQL_HOST=database
    ports:
      - "8081:8081"
    links:
      - database

  product:
    image: ziembatomasz/product:1.0
    environment:
      - MYSQL_HOST=database
    ports:
      - "8082:8082"
    links:
      - database

  database:
    image: ziembatomasz/database:1.0
    ports:
      - "3306:3306"
